#!/usr/bin/env python3
"""
Setup environment script for Neo4j and AWS Bedrock workshop.

This script:
1. Reads CDK deployment outputs from CloudFormation
2. Validates Bedrock model access
3. Writes configuration to .env file

Run this after deploying the CDK stacks:
    cdk deploy --all
    python setup_env.py
"""

import json
import os
import sys
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

# Stack names from CDK deployment
MONITORING_STACK_NAME = "Neo4jWorkshopMonitoring"
BEDROCK_STACK_NAME = "Neo4jWorkshopBedrock"


def get_aws_region() -> str:
    """Get AWS region from environment or default."""
    return os.getenv("AWS_REGION", "us-east-1")


def get_stack_outputs(stack_name: str, region: str) -> dict:
    """
    Get outputs from a CloudFormation stack.

    Args:
        stack_name: Name of the CloudFormation stack.
        region: AWS region.

    Returns:
        Dictionary of output key-value pairs.
    """
    cfn = boto3.client("cloudformation", region_name=region)

    try:
        response = cfn.describe_stacks(StackName=stack_name)
        if not response["Stacks"]:
            print(f"Warning: Stack {stack_name} not found")
            return {}

        outputs = response["Stacks"][0].get("Outputs", [])
        return {o["OutputKey"]: o["OutputValue"] for o in outputs}

    except ClientError as e:
        if "does not exist" in str(e):
            print(f"Warning: Stack {stack_name} does not exist")
            return {}
        raise


def validate_bedrock_access(region: str) -> dict:
    """
    Validate access to required Bedrock models.

    Args:
        region: AWS region to check.

    Returns:
        Dictionary with model access status.
    """
    bedrock = boto3.client("bedrock", region_name=region)

    models_to_check = {
        "claude": "anthropic.claude-3-5-sonnet-20241022-v2:0",
        "titan_embeddings": "amazon.titan-embed-text-v2:0",
    }

    access_status = {}

    print("\nValidating Bedrock model access...")
    for name, model_id in models_to_check.items():
        try:
            # Try to get model details - this will fail if not accessible
            response = bedrock.list_foundation_models(
                byProvider=model_id.split(".")[0]
            )
            # Check if specific model is available
            available_models = [m["modelId"] for m in response.get("modelSummaries", [])]

            if any(model_id.startswith(m.replace(":0", "")) for m in available_models):
                print(f"  [OK] {name}: {model_id}")
                access_status[name] = True
            else:
                print(f"  [WARNING] {name}: {model_id} - not found in available models")
                access_status[name] = False

        except ClientError as e:
            print(f"  [ERROR] {name}: {e}")
            access_status[name] = False

    return access_status


def load_existing_env(env_path: Path) -> dict:
    """
    Load existing .env file if it exists.

    Args:
        env_path: Path to .env file.

    Returns:
        Dictionary of existing environment variables.
    """
    existing = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    existing[key.strip()] = value.strip()
    return existing


def write_env_file(env_path: Path, config: dict):
    """
    Write configuration to .env file.

    Args:
        env_path: Path to .env file.
        config: Dictionary of configuration values.
    """
    content = """# AWS Configuration (Auto-generated by setup_env.py)
AWS_REGION={region}
AWS_BEDROCK_MODEL_ID={bedrock_model_id}
AWS_BEDROCK_EMBEDDING_MODEL_ID={bedrock_embedding_model_id}
AWS_BEDROCK_AGENT_ID={bedrock_agent_id}
AWS_BEDROCK_AGENT_ALIAS_ID={bedrock_agent_alias_id}

# Embedding Configuration
EMBEDDING_DIMENSIONS={embedding_dimensions}

# Neo4j Configuration (User-configured)
NEO4J_URI={neo4j_uri}
NEO4J_USERNAME={neo4j_username}
NEO4J_PASSWORD={neo4j_password}
NEO4J_VECTOR_INDEX_NAME={neo4j_vector_index_name}

# CloudWatch Configuration (From CDK deployment)
APP_LOG_GROUP={app_log_group}
AGENT_LOG_GROUP={agent_log_group}
""".format(**config)

    with open(env_path, "w") as f:
        f.write(content)

    print(f"\nWrote configuration to {env_path}")


def main():
    """Main entry point."""
    print("=" * 60)
    print("Neo4j and AWS Bedrock Workshop - Environment Setup")
    print("=" * 60)

    region = get_aws_region()
    print(f"\nUsing AWS region: {region}")

    # Get existing configuration
    env_path = Path(__file__).parent / ".env"
    existing = load_existing_env(env_path)

    # Get CDK stack outputs
    print("\nReading CDK stack outputs...")
    monitoring_outputs = get_stack_outputs(MONITORING_STACK_NAME, region)
    bedrock_outputs = get_stack_outputs(BEDROCK_STACK_NAME, region)

    # Validate Bedrock access
    access_status = validate_bedrock_access(region)

    if not all(access_status.values()):
        print("\n[WARNING] Some Bedrock models may not be accessible.")
        print("Please enable model access in the Bedrock console:")
        print(f"  https://{region}.console.aws.amazon.com/bedrock/home?region={region}#/modelaccess")

    # Build configuration
    config = {
        "region": region,
        "bedrock_model_id": existing.get(
            "AWS_BEDROCK_MODEL_ID", "anthropic.claude-3-5-sonnet-20241022-v2:0"
        ),
        "bedrock_embedding_model_id": existing.get(
            "AWS_BEDROCK_EMBEDDING_MODEL_ID", "amazon.titan-embed-text-v2:0"
        ),
        "bedrock_agent_id": existing.get("AWS_BEDROCK_AGENT_ID", ""),
        "bedrock_agent_alias_id": existing.get("AWS_BEDROCK_AGENT_ALIAS_ID", ""),
        "embedding_dimensions": existing.get("EMBEDDING_DIMENSIONS", "1024"),
        "neo4j_uri": existing.get("NEO4J_URI", ""),
        "neo4j_username": existing.get("NEO4J_USERNAME", "neo4j"),
        "neo4j_password": existing.get("NEO4J_PASSWORD", ""),
        "neo4j_vector_index_name": existing.get("NEO4J_VECTOR_INDEX_NAME", "chunkEmbeddings"),
        "app_log_group": monitoring_outputs.get("AppLogGroupName", ""),
        "agent_log_group": monitoring_outputs.get("AgentLogGroupName", ""),
    }

    # Write .env file
    write_env_file(env_path, config)

    print("\n" + "=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. Update NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD in .env")
    print("  2. Run: pip install -e .")
    print("  3. Start Lab 5 notebooks")

    return 0


if __name__ == "__main__":
    sys.exit(main())
